services:
  shop-database:
    image: postgres:16.1-alpine
    container_name: pizza_shop_db_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: pizza_shop
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pizza_shop"]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - app_network

  shop-production:
    build:
      context: .
      dockerfile: Dockerfile
    image: pizza_shop_app_production_image
    container_name: pizza_shop_app_production_container
    restart: unless-stopped
    depends_on:
      shop-database:
        condition: service_healthy
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    networks:
      - app_network
volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
